### ISSUE TITLE
As a user, give a warning when adding tasks that have clashes with other tasks

### ISSUE THREAD

**Issue by pznp111** [cs2103aug2015-w10-4j/main#1]
...so that I can reschedule the task

**Comment by bluepropane** [comment]
however, if I do not wish to reschedule the clash, I will still be able to go ahead and create the task.

**Comment by m133225** [comment]
pushed to milestone V0.2 as we have not implemented items with start & end time

**Comment by pznp111** [comment]
close becouse it is the same as one of the other issue
