### ISSUE TITLE
Allow UI to have 2 different displays for tasks (modify showTasks)

### ISSUE THREAD

**Issue by m133225** [cs2103aug2015-w10-4j/main#67]
# UPDATE

**Display categories have been changed**

default:
display up to 3 items of each category: nearest date, 2nd nearest date, floating tasks
- A list of tasks (maximum 9) will be passed to UI

filtered:
display all items given

**Comment by raisfathin** [comment]
Done. 9ab85471226d000d41599962235350cb51c43a90
