### ISSUE TITLE
Allow Parser to identify command for deleting/editing all related recurring tasks

### ISSUE THREAD

**Issue by m133225** [cs2103aug2015-w10-4j/main#68]
e.g. "delete 1 related" to delete all recurring tasks related to task 1
or "edit 1 related loc nus" to set the location to nus for all recurring tasks related to task 1

**Comment by m133225** [comment]
Pushed to V0.4.

**Comment by pznp111** [comment]
may not be necessary and very useful
deleting related task might delete some tasks that user actually does not wish to delete
or simply use search and delete all to complete such function

**Comment by m133225** [comment]
Not implemented. Does not provide that much functionality to the user.
