### ISSUE TITLE
Enable parser to parse tasks with escaped keywords in description

### ISSUE THREAD

**Issue by m133225** [cs2103aug2015-w10-4j/main#73]
e.g. "add Watch \by Tomorrow" will parse and return a task description of "Watch by Tomorrow"

**Comment by pznp111** [comment]
1.1 add by this friday loc nus(add loc nus by this friday)
1.2. add loc loc
1.3. add every 2 days for 2(add every 2 days for 2 loc nus)
1.4 add by this friday

**Comment by pznp111** [comment]
done
